### ISSUE TITLE
Issues when interacting with other plugins

### ISSUE THREAD

**Issue by chrisgrieser** [dvcrn/obsidian-filename-heading-sync#22]
I love this small but nifty plugin, but I think it should keep track of other plugins that it might break. when not adding Kanbans by the Kanban Plugin to the ignored list, the Kanbans will break. And I *think* it also breaks the index file of the new Longform plugin, but I am not totally certain about that.

**Comment by dvcrn** [comment]
It's hard for me to maintain a compatibility list with all the different plugins that exist. 

We could do something community maintained but this relies on pull requests and people coming forth to submit fixes

**Comment by chrisgrieser** [comment]
Yeah, keeping up with all plugins will be much. 

Well, I do not really have the knowledge to submit fixes, but I do not mind reporting plugins that do not interact well with this plugin.

The Kanban-Notes and the Longform-Index-Files have characteristic properties in the yaml-header, so it should be possible to scan for those things, right?

The Kanban notes all contain this line in the yaml header
```
kanban-plugin: basic
```

The longform Index file has no unique item in the yaml header, but I think it's still distinct due to all the mentionings of scenes and stuff. You could also maybe wait until the dev maybe implements a unique yaml item.
```
---
version: 1
drafts:
  - name: first
    folder: first
    scenes:
      - Abstract
      - Prior Research
      - Introduction
      - Conclusion
  - name: second
    folder: second
    scenes:
      - Abstract
---
```
